In [2]:
def fib(n):
    seq = [1.]
    if n <= 1: pass
    else: 
        seq.append(1.)        
        for i in range(n-2):
            new = seq[-2] + seq[-1]
            seq.append(new) 
    return seq

In [3]:
for i in range(10):
    print (fib(i))

[1.0]
[1.0]
[1.0, 1.0]
[1.0, 1.0, 2.0]
[1.0, 1.0, 2.0, 3.0]
[1.0, 1.0, 2.0, 3.0, 5.0]
[1.0, 1.0, 2.0, 3.0, 5.0, 8.0]
[1.0, 1.0, 2.0, 3.0, 5.0, 8.0, 13.0]
[1.0, 1.0, 2.0, 3.0, 5.0, 8.0, 13.0, 21.0]
[1.0, 1.0, 2.0, 3.0, 5.0, 8.0, 13.0, 21.0, 34.0]


In [4]:
import time

start_time = time.time()
fib(20000)
end_time = time.time()

# at the end of the program:
print("%f seconds" % (end_time - start_time))

0.011563 seconds


In [5]:
import cProfile
cProfile.run('fib(500)')

         503 function calls in 0.000 seconds

   Ordered by: standard name

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000    0.000    0.000 <ipython-input-2-7c07d5b5a814>:1(fib)
        1    0.000    0.000    0.000    0.000 <string>:1(<module>)
        1    0.000    0.000    0.000    0.000 {built-in method builtins.exec}
      499    0.000    0.000    0.000    0.000 {method 'append' of 'list' objects}
        1    0.000    0.000    0.000    0.000 {method 'disable' of '_lsprof.Profiler' objects}




In [6]:
# Fib didn't work with numpy very well

In [7]:
import sys
print(sys.getrecursionlimit())
sys.setrecursionlimit(11000)
print(sys.getrecursionlimit())


3000
11000


In [8]:
def squares(n):
    if n <= 1:
        return [1]
    else:
        seq = squares(n-1)
        seq.append(n*n)
        return seq

In [9]:
for i in range(1,10):
    print (squares(i))

[1]
[1, 4]
[1, 4, 9]
[1, 4, 9, 16]
[1, 4, 9, 16, 25]
[1, 4, 9, 16, 25, 36]
[1, 4, 9, 16, 25, 36, 49]
[1, 4, 9, 16, 25, 36, 49, 64]
[1, 4, 9, 16, 25, 36, 49, 64, 81]


In [10]:
import time

start_time = time.time()
squares(10)
end_time = time.time()

# at the end of the program:
print("%f seconds" % (end_time - start_time))

0.000060 seconds


In [11]:
import time
import sys
sys.setrecursionlimit(21000)

start_time = time.time()
squares(20000)
end_time = time.time()

# at the end of the program:
print("%f seconds" % (end_time - start_time))

0.028748 seconds


In [12]:
import cProfile
cProfile.run('squares(20000)')

         40002 function calls (20003 primitive calls) in 0.028 seconds

   Ordered by: standard name

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
  20000/1    0.025    0.000    0.027    0.027 <ipython-input-8-50d13c5dd8df>:1(squares)
        1    0.000    0.000    0.028    0.028 <string>:1(<module>)
        1    0.000    0.000    0.028    0.028 {built-in method builtins.exec}
    19999    0.002    0.000    0.002    0.000 {method 'append' of 'list' objects}
        1    0.000    0.000    0.000    0.000 {method 'disable' of '_lsprof.Profiler' objects}




In [13]:
def squares2(n):
    if n <= 1:
        return [1]
    else:
        seq = []
        for i in range(1,n):
            seq.append(i*i)
        return seq

In [14]:
import time

start_time = time.time()
squares2(20000)
end_time = time.time()

# at the end of the program:
print("%f seconds" % (end_time - start_time))

0.003575 seconds


In [15]:
for i in range(1,10):
    print (squares2(i))

[1]
[1]
[1, 4]
[1, 4, 9]
[1, 4, 9, 16]
[1, 4, 9, 16, 25]
[1, 4, 9, 16, 25, 36]
[1, 4, 9, 16, 25, 36, 49]
[1, 4, 9, 16, 25, 36, 49, 64]


In [16]:
import cProfile
cProfile.run('squares2(20000)')

         20003 function calls in 0.009 seconds

   Ordered by: standard name

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.007    0.007    0.009    0.009 <ipython-input-13-5c6731cb3b0c>:1(squares2)
        1    0.000    0.000    0.009    0.009 <string>:1(<module>)
        1    0.000    0.000    0.009    0.009 {built-in method builtins.exec}
    19999    0.002    0.000    0.002    0.000 {method 'append' of 'list' objects}
        1    0.000    0.000    0.000    0.000 {method 'disable' of '_lsprof.Profiler' objects}




In [17]:
x1 = squares(20000)
x2 = squares2(20000)
for idx, (x,y) in enumerate(zip(x1,x2)):
    if (x != y):
        print (idx,x,y)
        break


In [18]:
import numpy as np
def squares3(n):

    seq = np.zeros(n, dtype=np.int)
    for i in range(1, n+1):
        seq[i-1] = i * i            
    return seq

In [19]:
import time

start_time = time.time()
squares3(20000)
end_time = time.time()

# at the end of the program:
print("%f seconds" % (end_time - start_time))

0.004147 seconds


In [20]:
import cProfile
cProfile.run('squares3(20000)')

         5 function calls in 0.004 seconds

   Ordered by: standard name

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.004    0.004    0.004    0.004 <ipython-input-18-d2e06aa2d598>:2(squares3)
        1    0.000    0.000    0.004    0.004 <string>:1(<module>)
        1    0.000    0.000    0.004    0.004 {built-in method builtins.exec}
        1    0.000    0.000    0.000    0.000 {built-in method numpy.zeros}
        1    0.000    0.000    0.000    0.000 {method 'disable' of '_lsprof.Profiler' objects}




In [21]:
#Thanks Drason!
def squares4(n):
    return [i * i for i in range(1, n+1)]

start_time = time.time()
squares4(20000)
end_time = time.time()

# at the end of the program:
print("%f seconds" % (end_time - start_time))

0.003010 seconds


In [22]:
for i in range(1,10):
    print (squares(i))
    print (squares3(i))
    print (squares4(i))

[1]
[1]
[1]
[1, 4]
[1 4]
[1, 4]
[1, 4, 9]
[1 4 9]
[1, 4, 9]
[1, 4, 9, 16]
[ 1  4  9 16]
[1, 4, 9, 16]
[1, 4, 9, 16, 25]
[ 1  4  9 16 25]
[1, 4, 9, 16, 25]
[1, 4, 9, 16, 25, 36]
[ 1  4  9 16 25 36]
[1, 4, 9, 16, 25, 36]
[1, 4, 9, 16, 25, 36, 49]
[ 1  4  9 16 25 36 49]
[1, 4, 9, 16, 25, 36, 49]
[1, 4, 9, 16, 25, 36, 49, 64]
[ 1  4  9 16 25 36 49 64]
[1, 4, 9, 16, 25, 36, 49, 64]
[1, 4, 9, 16, 25, 36, 49, 64, 81]
[ 1  4  9 16 25 36 49 64 81]
[1, 4, 9, 16, 25, 36, 49, 64, 81]


In [162]:
import time

start_time = time.time()
fib2(20000)
end_time = time.time()

# at the end of the program:
print("%f seconds" % (end_time - start_time))

0.016060 seconds


In [163]:
x = fib(20000)
y = fib2(20000)
for idx, (xn, yn) in enumerate(zip(x,y)):
    if xn != yn:
        print (idx)
        break
        
print (x[idx])
print (y[idx])

78
1.447233402467622e+16
1.4472334024676221e+16


In [89]:
x = [1,2]
y = [4,5]
for i, (xn,yn) in enumerate( zip(x,y)):
    print (i, xn)

0 1
1 2


In [66]:
x = np.zeros(3)
print (x)
x[0] = 1
print (x)
for i in range(2,3): print (i)

[0. 0. 0.]
[1. 0. 0.]
2
